### ISSUE TITLE
maybe glm::perspective should take a degree as the first parameter, not a radian

### ISSUE THREAD

**Issue by ZhangZekun** [JoeyDeVries/LearnOpenGL#106]
Hi,
   Thanks for your tutorial. It really help a lot.
   I followed your tutorial, and I found that you use a radian as the the first parameter of the glm::perspective, which make things a little strange.
   I read the source code of glm:::perspective and found this:
```
template <typename T>
	GLM_FUNC_QUALIFIER detail::tmat4x4<T, defaultp> perspective
	(
		T const & fovy,
		T const & aspect,
		T const & zNear,
		T const & zFar
	)
	{
		assert(aspect != static_cast<T>(0));
		assert(zFar != zNear);

#ifdef GLM_FORCE_RADIANS
		T const rad = fovy;
#else
#		pragma message("GLM: perspective function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
		T const rad = glm::radians(fovy);
#endif
```
  It seems that we should define GLM_FORCE_RADIANS first so that we can use a radian as the first parameter, otherwise we should use a degree.
  Thanks for your tutorial again!

**Comment by eliemichel** [comment]
You must be reading an old version of glm cause `GLM_FORCE_RADIANS` has been removed since [GLM 0.9.6.0](https://github.com/g-truc/glm/releases/tag/0.9.6.0) (August 2015), see release notes. ;) It is now on by default, so yes the fov argument must be in radians.
