### ISSUE TITLE
cmake Configuration

### ISSUE THREAD

**Issue by Polytonic** [JoeyDeVries/LearnOpenGL#11]
I recently worked my way through the tutorials, and I had some problems getting all the dependencies installed (campus computer, no admin rights, etc.) so I put together [Glitter](https://github.com/Polytonic/Glitter). Basically it bundles all the dependencies as submodules and statically compiles/links to avoid any dll-copying or installation headaches. I've verified that it works under Mac OSX (10.10) for makefiles/Xcode and Windows (8.1) (VS2013/15), and I'm reasonably confident it builds under most standard flavors of Linux. 

Is this of any interest or use to you? Could possibly try to integrate some of it into this repository's cmake configuration or something. In any case, thanks for the tutorials! I found them immensely helpful. :smile:

**Comment by JoeyDeVries** [comment]
Thank you! Glitter looks awesome; I love how you recursively include the vendor's Github repositories. I should probably use something similar for the includes folder as well.

I'm not sure if it would fit well with the current structure of the repository, but I think it might. Almost all dependancies are open-source and posted on Github; although I do plan to soon also add the irrKlang library for audio that isn't open-source, but that could be the exception to the rule.

The current repository works, and creates proper projects and solutions so it's not necessary, but if you're willing to invest the time to make it less DLL-dependant and statically build the libraries from their sources I think most people (and myself) would appreciate it. If so, try to keep the CMakeLists.txt as close to the original as possible; like the directory/sub-directory structure of source files, copy-ing of shader files and the user configuraton files for Visual Studio as I like it as it is right now :)

If you want I can add a reference to your Glitter project in the 'Code repository' page?

**Comment by Polytonic** [comment]
Depending on my time commitments, I can put a few hours towards this again next week. I'm still pretty new to cmake though, so I'm not sure how much I can realistically accomplish without breaking existing things. 

Feel free to add a reference if you think it will help others!

**Comment by JoeyDeVries** [comment]
Of course, like I said it's not necessary as the current system works so don't worry if you don't have the time to invest in it, it simply makes everything more elegant ;) 

I'll add a reference to Glitter somewhere today :D

**Comment by JoeyDeVries** [comment]
I added a small section of text about Glitter. Feel free to edit it more to your liking if you want :)

**Comment by Polytonic** [comment]
Thanks for adding the reference! 

I took a stab at integration earlier this morning, and I think you're right. Glitter doesn't fit particularly well into the current, given everything already works. I'm hesitant to possibly break something that already works reasonably well. Perhaps maybe just adding a link to Glitter on the website instead, maybe to help people who are having installation/setup issues with OpenGL? Your call.

Do you have any plans to integrate a physics engine? I was considering adding Bullet to Glitter.  

P.S. Looks like the website was featured on [HackerNews](https://news.ycombinator.com/item?id=9751666), if you didn't see it over the weekend.

**Comment by JoeyDeVries** [comment]
Hehe yeah I had such an idea, then let's just keep it as an reference; either way I'm sure it will help people. I'll also post a link later today on the 'Code repository' article and add your project to the 'Additional resources' of the 'Windowing' tutorials :)

Integrating a physics library is low on my to-do list so don't count on it yet.

Yeah I saw it, someone has been active posting the website all over the internet; also a large post on reddit.com/r/programming. The website views went skyrocket that day :D
