### ISSUE TITLE
Roughness value should be normalized.

### ISSUE THREAD

**Issue by JesseRMeyer** [JoeyDeVries/LearnOpenGL#111]
https://github.com/JoeyDeVries/LearnOpenGL/blob/cdceb36d254e5e2d4f9b4dc28e99ca16e0be7a6c/src/6.pbr/1.2.lighting_textured/1.2.pbr.fs#L87

Hi. The retrieved texture values here are in the [0, 255] range, but roughness is a normalized quantity between 0 and 1, and I'm not seeing where this mapping is taking place. It may be a bug?

Jesse

**Comment by JoeyDeVries** [comment]
8-bit per component RGB(A) textures sampled in GLSL with the `texture` function always return normalized color values between [0, 1].
