### ISSUE TITLE
The given arbitrary 3d axis rotation matrix only works with normalized axis.

### ISSUE THREAD

**Issue by theof** [JoeyDeVries/LearnOpenGL#112]
glm::rotate takes care of normalizing the given vector.
However, it might be worth to hint readers about that in case they wish to implement their own matrix manipulation functions. I can PR that later this week if you agree.

Awesome tutorial by the way !

**Comment by JoeyDeVries** [comment]
It indeed seems I haven't mentioned this yet in the Transformations tutorial so I've added it in; thanks for letting me know! If you find any code occurrence that is not rotating around a Cartesian axis which isn't normalized then yes, please make a PR, thank you!
