### ISSUE TITLE
Breakout code?

### ISSUE THREAD

**Issue by Busata** [JoeyDeVries/LearnOpenGL#12]
Hello, first of all thanks for the great tutorial! But could it be that the breakout code is missing from this repository?

**Comment by JoeyDeVries** [comment]
Yes you're right it is indeed missing. I do plan to eventually place it on GitHub as well (in a different repository) but haven't yet reserved the time for that. Mostly because it uses a bit more 3rd party libraries than the tutorials and thus requires some extra efforts on the CMake side.

**Comment by asma-AH** [comment]
thank you for your great tutorials .. really thank you ! 
but i have unresolved external errors after i generate the project with cmake 
how can i solve this problem ?

**Comment by JoeyDeVries** [comment]
@asma-AH An unresolved external symbol error frequently means that there is some decleration of the function (often found in header files), but it couldn't find the actual definition of the function in the code during the linking step. This is often the case with external libraries; it found the header file, but couldn't properly link the actual .lib or .dll file and thus the definition was missing.

Check the type of library (GLFW, SOIL, Assimp or GLEW) that is giving these errors and compile these yourselves; that should most likely get rid of the errors. It's likely that the pre-compiled libraries included in the package didn't work for your setup.

**Comment by oceancx** [comment]
really looking forward to the breakout github repo

**Comment by Alexeir7** [comment]
I'm waiting for it too, any updates on that?

**Comment by Shot511** [comment]
Hey,
The whole Breakout code (with slight modifications) is available here: https://github.com/Shot511/GameBreakout

It should build well both on Windows and Linux.
