### ISSUE TITLE
Why casting float to float?

### ISSUE THREAD

**Issue by roxlu** [JoeyDeVries/LearnOpenGL#124]
I guess you intended the `nrSamples` to be an int https://github.com/JoeyDeVries/LearnOpenGL/blob/master/src/6.pbr/2.1.2.ibl_irradiance/2.1.2.irradiance_convolution.fs#L40 ? 

I'm wondering why you would cast it there; and if it would make a difference to use int/float?

**Comment by JoeyDeVries** [comment]
It looks like `nrSamples` indeed used to be an int. I'd probably just stick to a float there so the cast can be removed; no real need for int arithmetic.
