### ISSUE TITLE
The site is unavailable from Russia

### ISSUE THREAD

**Issue by Marat-Tanalin** [JoeyDeVries/LearnOpenGL#145]
Apparently because it is hosted on Digital Ocean which IPs are mass-blocked by law in Russia.

**Comment by JoeyDeVries** [comment]
Ahh shit. There's not too much I can do there. I really like Digital Ocean as it allows me to set up a custom hosting system which perfectly suits LearnOpenGL's needs. I'm not really looking forward to re-doing this whole setup on a different host with no guarantee that it won't be blocked in the future either.

**Comment by Vyraax** [comment]
I guess you could still use a vpn or a proxy to bypass the censorship?

**Comment by Marat-Tanalin** [comment]
I see a couple of possible options from the site-owner perspective:

* buy a dedicated (not shared with any other site or account) IP from a range not blocked in Russia;

* use a third-party hosting for transparent proxying the current site with no need for changing its architecture.

From the user perspective, workarounds like VPN are better than nothing but they have their serious downsides such as forcing using a web browser different from the one the user usually use and is comfortable with.

**Comment by Anton-V-K** [comment]
If the original report was about https://learnopengl.com/ , then probably the block isn't there any more - I can access the site without VPN or proxies (SkyNet provider in Saint-Petersburg).

**Comment by Marat-Tanalin** [comment]
Not via MGTS unfortunately. Some internet providers use different blocking approaches or don’t block some prohibited sites at all.

**Comment by ArtemBorodinEvgenyevich** [comment]
> If the original report was about https://learnopengl.com/ , then probably the block isn't there any more - I can access the site without VPN or proxies (SkyNet provider in Saint-Petersburg).

Unfortunately, It's still unavailable using mobile internet providers like "MegaFon" / "MTC"

**Comment by Marat-Tanalin** [comment]
Telegram is unblocked in Russia today, so LearnOpenGL is now finally available from Russia too.

**Comment by JoeyDeVries** [comment]
That's great news, happy to hear that!
