### ISSUE TITLE
#bug [hello_triangle_indexed] indices order is wrong

### ISSUE THREAD

**Issue by happyfire** [JoeyDeVries/LearnOpenGL#163]
Please look at the indices in hello_triangle_indexed.cpp:
```
unsigned int indices[] = {  // note that we start from 0!
        0, 1, 3,  // first Triangle
        1, 2, 3   // second Triangle
    };
```
The order is clockwise, it is wrong because by default opengl is right handed. The right order is:
```
unsigned int indices[] = {
		0, 3, 1,
		1, 3, 2
	};
```
But why the triangles are still displayed? Because by default the GL_CULL_FACE is not enabled.
If you call glEnable(GL_CULL_FACE); before draw call, you will find there is nothing drawn if use the wrong order.

**Comment by MMJoeyDeVries** [comment]
It's not a bug. It's done this way on purpose. If I were to lay it out correctly the order would seem kind of 'random' to the unaware reader, which could confuse him/her. It's super minor, but these little things do help towards the learning journey if people are just starting out in my opinion. 

I've discussed face culling later here: https://learnopengl.com/Advanced-OpenGL/Face-culling

**Comment by JoeyDeVries** [comment]
It's not a bug. It's done this way on purpose. If I were to lay it out correctly the order would seem kind of 'random' to the unaware reader, which could confuse him/her. It's super minor, but these little things do help towards the learning journey if people are just starting out in my opinion. 

I've discussed face culling later here: https://learnopengl.com/Advanced-OpenGL/Face-culling
