### ISSUE TITLE
Please fix infinity loops

### ISSUE THREAD

**Issue by samrrr** [JoeyDeVries/LearnOpenGL#164]
Somebody add "fix" and now its infinity loop. https://github.com/JoeyDeVries/LearnOpenGL/commit/dcdf94fce79f02cf66390ed337ffd09cdc63b252
I think add unsigned to loops is bad idea.

**Comment by JoeyDeVries** [comment]
Ahhh, that's how it got in there.; saw it mentioned before and didn't remember using unsigned ints there. It's added to my list of notes when doing a big code change for 3rd revision site, I'm currently at PBR chapters so pretty close.
