### ISSUE TITLE
Forget delete shader program

### ISSUE THREAD

**Issue by imyuewu** [JoeyDeVries/LearnOpenGL#167]
This is may not some issues, but something confused me. In section Hello_Triangle, after reading exercise source code, I found it seems u don't delete the shader program. Is this the case, or just someone forget to delete it?

**Comment by JoeyDeVries** [comment]
It's not necessary as OpenGL clears out all resources at program exit, but I did miss the call to glDeleteProgram indeed so for completeness' sake I've added it to all relevant examples, thank you! :)
