### ISSUE TITLE
Geometry shaders come *after* tessellation, not before.

### ISSUE THREAD

**Issue by NicolBolas** [JoeyDeVries/LearnOpenGL#17]
Your [pipeline picture](http://learnopengl.com/img/getting-started/pipeline.png) is incorrect. The geometry shader comes after the tessellation process, not before.

Also, since your tutorial is limited to GL 3.3, you probably shouldn't be talking about tessellation at all.

**Comment by JoeyDeVries** [comment]
You're right! I'll find some time today/tommorow to fix the image, thank you!

And yes, the tutorials are geared at 3.3, but I'd also like to discuss more modern topics. Of course when I start with tesselation I'll strongly mention its core since 4.0.

**Comment by JoeyDeVries** [comment]
I've updated the pipeline image. I agree that it's probably for the best to leave tesselation completely out of the picture as it might indeed confuse readers so I left it out of the pipeline. Once I do write up a tutorial regarding tesselation I'll (properly) describe where it fits in the pipeline. Thanks, once again!
