### ISSUE TITLE
cmake build err in Mac OS Catalina 10.15.4

### ISSUE THREAD

**Issue by jinruozai** [JoeyDeVries/LearnOpenGL#170]
brew install cmake assimp glm glfw
mkdir build
cd build
cmake -G "Xcode" ..

print:

-- The C compiler identification is AppleClang 11.0.3.11030032
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found GLM: /usr/local/include  
-- GLM_INCLUDE_DIR = /usr/local/include
-- GLM included at /usr/local/include
-- Found GLFW3: /usr/local/lib/libglfw3.a  
-- Found GLFW3 in /usr/local/include
-- Found ASSIMP: /usr/local/lib/libassimp.dylib
-- Found ASSIMP in /usr/local/include
-- Configuring done
CMake Error at CMakeLists.txt:197 (add_executable):
  No SOURCES given to target: 1.getting_started__4.4.textures_exercise3

CMake Error at CMakeLists.txt:197 (add_executable):
  No SOURCES given to target: 1.getting_started__4.5.textures_exercise4

CMake Error at CMakeLists.txt:197 (add_executable):
  No SOURCES given to target: 1.getting_started__4.3.textures_exercise2

what's wrong with it ~help

**Comment by JoeyDeVries** [comment]
Oh oops, I renamed a few directories but forgot to change the `CMakeLists.txt` file. It should be fixed now if you pull, thanks!

**Comment by jinruozai** [comment]
It completely solved my problem~Thank U
