### ISSUE TITLE
compiling text_rendering example 

### ISSUE THREAD

**Issue by madjestic** [JoeyDeVries/LearnOpenGL#171]
Hey, Joey

I find it a bit tricky to compile `text_rendering` example.  CMake file mentions 
> # due to trickier build setups (other libs rarely used everywhere else) these examples won't compile through CMake, but source code is available.

Could you elaborate a bit?  For instance `#include "Shader.h"` is using `shader.Program` later on, but I don't see any source files that implement Program for Shader class...

Thanks
Vlad

**Comment by JoeyDeVries** [comment]
The reason it's trickier is that it requires FreeType.lib for it to compile successfully, so you'll want to get the FreeType lib/headers yourself and link them for that specific project. The source code itself should compile then, but it wouldn't surprise me if there's still a mistake in there as I haven't tested that project's example code since the book changes yet.

**Comment by rbarkmore** [comment]
Hello,  I was able to get the text_rendering example to work, following your instructions.  First, uncomment line 167 '2.text_rendering' in the CMakeList.txt file and run cmake.  This will create the project for the example.  Next, compile Freetype2 as a static lib using VS2013 and manually add the Freetype files to the project.  You will need to supply a font for Freetype to use.  

There are two 'main()'s in 'text_rendering.cpp', so comment out from line 183 to line 208.   Also, in 'text_rendering.cpp', change from 'shader.Use' to 'shader.use' (lowercase), and change from 'shader.Program' to 'shader.ID', make both changes in two places each.  

If you like, I could submit a pull request.  Rich.

BTW, the tutorials are great!

![screenshot](https://user-images.githubusercontent.com/56879808/84953873-54bc6c00-b0c2-11ea-86f4-4e89c23544f5.png)

**Comment by JoeyDeVries** [comment]
Amazing, thank you @rbarkmore ! If you can, yes please; keep the CMakeLists.txt line commented tho, as it'll cause the solution compile to break if people haven't set it up manually.
