### ISSUE TITLE
Hi, JoeyDevries I have a question.

### ISSUE THREAD

**Issue by leeyunhome** [JoeyDeVries/LearnOpenGL#178]
Hello,

Sorry for leaving a question here.

I want to use opengl for yuv to rgp converting.
Instead of drawing the texture from the fragment shader right away
Can rgb data be stored in memory?
Can I use glgetpixels or glGetTexImage?

I only use opengl from yuv to rgb conversion and I only want to draw the converted data in qt.
This is to display the existing qt program without changing it.

Thank you.

**Comment by JoeyDeVries** [comment]
Yesss, you can render everything to a framebuffer and then use `glReadPixels` (https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glReadPixels.xhtml) on the resulting framebuffer to get the pixel data; that way you can process the result however you like :)

**Comment by leeyunhome** [comment]
> Yesss, you can render everything to a framebuffer and then use `glReadPixels` (https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glReadPixels.xhtml) on the resulting framebuffer to get the pixel data; that way you can process the result however you like :)

Thank you very much!!!
