### ISSUE TITLE
Identifier "logl_root" is undefined

### ISSUE THREAD

**Issue by nikhilAnayak** [JoeyDeVries/LearnOpenGL#187]
I'm trying to use the filesystem.h header file to load the image in the tutorial but it tells me that identifier "logl_root" is undefined. I'm not sure how to solve this problem and any help would be appreciated.

**Comment by rbarkmore** [comment]
Sound like a cmake issue.

Please start over, download a fresh copy of the repository.  Extract into a directory/folder of your choice, then don't change or rename that directory/folder.  Run cmake and build, then post your results here.  Thanks.
