### ISSUE TITLE
Can't  create shader using Shader class

### ISSUE THREAD

**Issue by Anastasiawangyx** [JoeyDeVries/LearnOpenGL#204]
hi, I am really having some trouble with the code in the chapter Shaders. I've created a `shader.h` file and `#include "shader.h"` in my `main.cpp` successfully. 
But when I tried to create a shader using ` Shader ourShader("4.1.texture.vs", "4.1.texture.fs");` , it throws an error as we write in the `shader.h` ,that is `ERROR::SHADER::FILE_NOT_SUCCESFULLY_READ`.
I added the `std::cout << e.what() << std::endl;` to see the error, and it is `ios_base::clear: unspecified iostream_category error`.
Because I'm not so familiar with the c++, so could anyone please give me any solutions?
Thanks!

**Comment by gameengineer** [comment]
Sounds like a file path issue. The program cant find the .vs and .fs shader files. Unless you put the fully qualified path Visial Studio will use relative paths to the file. It is relative to the .vcxproj file which is the project file. The .vs and .fs filename parameters of your ourShaders() object do not include a path to them so Visual Studio will assume to look for them where your project file is. 
 You can try this. Copy the shader files to the directory where your project file is located and see if that fixes that error.

**Comment by Anastasiawangyx** [comment]
> Sounds like a file path issue. The program cant find the .vs and .fs shader files. Unless you put the fully qualified path Visial Studio will use relative paths to the file. It is relative to the .vcxproj file which is the project file. The .vs and .fs filename parameters of your ourShaders() object do not include a path to them so Visual Studio will assume to look for them where your project file is.
> You can try this. Copy the shader files to the directory where your project file is located and see if that fixes that error.

Thank u for your reply!
I'm using macOS system so I use the clion IDE instead of VS. Actually in my code, I've put the `shader.h` file at the same level as the `main.cpp` , also with the `4.1.texture.vs` and `4.1.texture.fs`, that is why I use the relative path in my main.cpp. 
I changed my code and use the absolute path as `"/Users/myusername/Desktop/learnOpenGL/learn2/4.1.texture.vs"` and it works. But I still wonder why my former usage if wrong.
