### ISSUE TITLE
cmake build err in Mac OS Catalina 10.15.6

### ISSUE THREAD

**Issue by hu5980** [JoeyDeVries/LearnOpenGL#207]
Undefined symbols for architecture x86_64:
  "_FT_Done_Face", referenced from:
      _main in text_rendering.cpp.o
  "_FT_Done_FreeType", referenced from:
      _main in text_rendering.cpp.o
  "_FT_Init_FreeType", referenced from:
      _main in text_rendering.cpp.o
  "_FT_Load_Char", referenced from:
      _main in text_rendering.cpp.o
  "_FT_New_Face", referenced from:
      _main in text_rendering.cpp.o
  "_FT_Set_Pixel_Sizes", referenced from:
      _main in text_rendering.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../bin/7.in_practice/7.in_practice__2.text_rendering] Error 1
make[1]: *** [CMakeFiles/7.in_practice__2.text_rendering.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by hu5980** [comment]
SET(APPLE_LIBS ${APPLE_LIBS} ${GLFW3_LIBRARY} ${ASSIMP_LIBRARY} ${FREETYPE_LIBRARIES})

**Comment by rbarkmore** [comment]
@hu5980 if you have a chance, please try compiling the branch of PR #215 and please report the results, good or bad.  Since I don't have access to Mac OS, I can't test the effect of this PR.  Thank you in advance.

**Comment by tainzhi** [comment]
I have tested it **failed**.  My environmment is Mac OS 10.14.6 on HacMac

After I added freetype to CMakeLists.txt and installed freetype, the same compiled error is still there.

**Comment by rbarkmore** [comment]
@tainzhi  can you please post the error messages?  Thanks.

**Comment by upupming** [comment]
Also, make sure to add:

```cmake
find_package(Freetype REQUIRED)
```

**Comment by tainzhi** [comment]
@upupming solution works. Thanks very much

**Comment by noobxiaohai** [comment]
> SET(APPLE_LIBS ${APPLE_LIBS} ${GLFW3_LIBRARY} ${ASSIMP_LIBRARY} ${FREETYPE_LIBRARIES})

my mac system version is 10.15.7, I added ${FREETYPE_LIBRARIES} this in CMakeList.txt, but the same error exists,what can I do?

**Comment by noobxiaohai** [comment]
> Also, make sure to add:
> 
> ```cmake
> find_package(Freetype REQUIRED)
> ```
@tainzhi @upupming 
which line in CMakeList.txt do I need to add 'find_package(Freetype REQUIRED)'?

when I add find here

```cmake
# find the required packages
find_package(GLM REQUIRED)
message(STATUS "GLM included at ${GLM_INCLUDE_DIR}")
find_package(GLFW3 REQUIRED)
message(STATUS "Found GLFW3 in ${GLFW3_INCLUDE_DIR}")
find_package(ASSIMP REQUIRED)
message(STATUS "Found ASSIMP in ${ASSIMP_INCLUDE_DIR}")
# find_package(SOIL REQUIRED)
# message(STATUS "Found SOIL in ${SOIL_INCLUDE_DIR}")
# find_package(GLEW REQUIRED)
# message(STATUS "Found GLEW in ${GLEW_INCLUDE_DIR}")
find_package(Freetype REQUIRED)
```

this error appeared when i do 'make ../.'

xiaohai:build xiao$ cmake ../.
-- GLM_INCLUDE_DIR = /usr/local/include
-- GLM included at /usr/local/include
-- Found GLFW3 in /usr/local/include
-- Found ASSIMP: /usr/local/lib/libassimp.dylib
-- Found ASSIMP in /usr/local/include
CMake Error at /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Freetype (missing: FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/FindFreetype.cmake:157 (find_package_handle_standard_args)
  CMakeLists.txt:31 (find_package)


-- Configuring incomplete, errors occurred!

**Comment by tainzhi** [comment]
you should add `find_package(Freetype REQUIRED)` at the apple ifelse branch, just before the line `SET(APPLE_LIBS ${APPLE_LIBS} ${GLFW3_LIBRARY} ${ASSIMP_LIBRARY} ${FREETYPE_LIBRARIES})`, such as line 50
