### ISSUE TITLE
how to implement the Floating drag panel ?? 

### ISSUE THREAD

**Issue by Corezcy** [JoeyDeVries/LearnOpenGL#212]
as the title ,could you please tell me how to make a ui like that ? or where is the relevant code?
![image](https://user-images.githubusercontent.com/33271784/99551137-76fe4100-29f6-11eb-923f-3d825a28e0fd.png)

**Comment by JoeyDeVries** [comment]
This is from a library called IMGUI (https://github.com/ocornut/imgui). An amazing library for quickly rendering UI on top of your graphics code; can highly recommend checking it out.

**Comment by Corezcy** [comment]
> This is from a library called IMGUI (https://github.com/ocornut/imgui). An amazing library for quickly rendering UI on top of your graphics code; can highly recommend checking it out.

 I see the relevant code in README . My task is make a  gui for map simulation in autodrive aspect...... 
Going to do !~
