### ISSUE TITLE
PBR Rendering Output is Different from Website Screen Shot

### ISSUE THREAD

**Issue by drcxd** [JoeyDeVries/LearnOpenGL#219]
Project Output:

![test](https://user-images.githubusercontent.com/24535087/103258699-40580680-4964-11eb-9c1e-11aaf2713f32.png)

Website Screen Shot:

[Screen Shot](https://learnopengl.com/img/pbr/lighting_result.png)

Running project `6.pbr__1.1.lighting` gives output which is different from screen shot provided on the website. It can be seen that there is no smaller but brighter specular light on sphere in the first two columns whose roughness value is relatively smaller. Is there bugs in code?

**Comment by drcxd** [comment]
After I proceed to the next chapter, I found the code in that chapter, to be specific, in project `pbr__2.1.1.ibl_irradiance_conversion`, could give proper visual output: sphere in the first two columns with smaller and brighter specular light spot on it.

I compared the shader code of these two projects and found that it seems the following difference is the reason:

```
--- 1.1.pbr.fs	2020-12-29 14:58:15.435997800 -0500
+++ 2.1.1.pbr.fs	2020-12-29 15:00:32.881173700 -0500
@@ -29,7 +29,7 @@
     float denom = (NdotH2 * (a2 - 1.0) + 1.0);
     denom = PI * denom * denom;
 
-    return nom / max(denom, 0.001); // prevent divide by zero for roughness=0.0 and NdotH=1.0
+    return nom / denom;
 }
```

After I change the shader code in project `6.pbr__1.1lighting` to `return nom / denom;`, it gives following visual output
![test](https://user-images.githubusercontent.com/24535087/103311409-4b547a80-49e8-11eb-8fd2-3df26f53ce61.png)

Could you explain the reason why? 

From my perspective, it seems the 0.001 in the `max` function is preventing higher output returned by the function `DistributionGGX`.

**Comment by JoeyDeVries** [comment]
Great catch! It seems the max(x, 0.001) is clamped to a value too high from 0.0 and `denom` can apparently get pretty small (thus leaving a high return value). I've updated this to use a much smaller clamp value which brings back the results to how they look like without the clamp, while still preventing divide by zero.
