### ISSUE TITLE
[QUESTION].Getting Started: How comes we dont run glfwTerminate() in case glad fails to load? 

### ISSUE THREAD

**Issue by quadroli** [JoeyDeVries/LearnOpenGL#229]
eg, over [here](https://github.com/JoeyDeVries/LearnOpenGL/blob/master/src/1.getting_started/1.1.hello_window/hello_window.cpp#L40-L44)

**Comment by AnshulKanwar** [comment]
Hey did you find the answer?

**Comment by quadroli** [comment]
no, do you happen to know?
