### ISSUE TITLE
There's no vec1 type in GLSL

### ISSUE THREAD

**Issue by ButylLee** [JoeyDeVries/LearnOpenGL#265]
According to OpenGL [wiki](https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)#Vectors), the *n* of vecn can only be 2, 3, 4. But in the chapter *Getting Started* - [*Shaders*](https://learnopengl.com/Getting-started/Shaders), it said *n* can be 1.

**Comment by JoeyDeVries** [comment]
Good catch, fixed it just now; thank you!
