### ISSUE TITLE
mac os build error

### ISSUE THREAD

**Issue by gionlime** [JoeyDeVries/LearnOpenGL#266]
Undefined symbols for architecture x86_64:
  "_FT_Done_Face", referenced from:
      _main in text_rendering.cpp.o
  "_FT_Done_FreeType", referenced from:
      _main in text_rendering.cpp.o
  "_FT_Init_FreeType", referenced from:
      _main in text_rendering.cpp.o
  "_FT_Load_Char", referenced from:
      _main in text_rendering.cpp.o
  "_FT_New_Face", referenced from:
      _main in text_rendering.cpp.o
  "_FT_Set_Pixel_Sizes", referenced from:
      _main in text_rendering.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../bin/7.in_practice/7.in_practice__2.text_rendering] Error 1
make[1]: *** [CMakeFiles/7.in_practice__2.text_rendering.dir/all] Error 2
make: *** [all] Error 2

**Comment by forest0** [comment]
Maybe you can take a look at #215

**Comment by gionlime** [comment]
Thanks
