### ISSUE TITLE
The link of Assimp downloads is not available

### ISSUE THREAD

**Issue by ButylLee** [JoeyDeVries/LearnOpenGL#269]
The link of Assimp downloads in section *Model Loading - Assimp - Building Assimp* seems not available today. It's said to download through GitHub directly instead.

See [Build Instructions](https://github.com/assimp/assimp/blob/master/Build.md) of Assimp.

**Comment by JoeyDeVries** [comment]
Good catch, I've just updated the article to feature their GitHub build instructions, thank you!
