### ISSUE TITLE
HDR example uses esoteric framebuffer support

### ISSUE THREAD

**Issue by jherico** [JoeyDeVries/LearnOpenGL#27]
https://github.com/JoeyDeVries/LearnOpenGL/blob/master/src/5.advanced_lighting/6.hdr/hdr.cpp#L107 refers to `GL_RGB16F` as the texture format for the color attachment, but many systems won't accept a framebuffer color attachment without an alpha channel.  Suggest you change it to `GL_RGBA16F`

**Comment by JoeyDeVries** [comment]
Interesting, I've updated the source code (both here and in the tutorial). Thank you!
