### ISSUE TITLE
windows cmake error

### ISSUE THREAD

**Issue by devenguo** [JoeyDeVries/LearnOpenGL#287]
CMake Error at C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Freetype (missing: FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.21/Modules/FindFreetype.cmake:162 (find_package_handle_standard_args)
  CMakeLists.txt:33 (find_package)

**Comment by ArcherEmiyaShirou** [comment]
hey!here is my solution that I just found and you can try it!

Create a new file called "FindFreetype.cmake" in cmake/modules/ and write some sentencens in it:

FIND_PATH( ASSIMP_INCLUDE_DIR assimp/mesh.h
	/usr/include
	/usr/local/include
	/opt/local/include
	${CMAKE_SOURCE_DIR}/includes
)
