### ISSUE TITLE
Problems with texture in model loading.

### ISSUE THREAD

**Issue by chenghuaWang** [JoeyDeVries/LearnOpenGL#292]
Hi, I am currently learning model loading chapter. I implemented model loading code using assimp according to the tutorial . My program works really well when displaying nanosuit.obj and backpack.obj file. However, there is a texture problem when displaying [sponza](http://hdri.cgtechniques.com/~sponza/files/).  I wonder if this is a problem that assimp parse obj file in uncorret way or the program is currently unable to handle such textures.

![image](https://user-images.githubusercontent.com/68260701/159146176-5ddc7684-32f7-44d2-9efa-ef2187049300.png)

Below are textures I used:
![prozor1](https://user-images.githubusercontent.com/68260701/159146359-822bc8dc-f1ef-43a6-b96a-27cbccfec028.JPG)
![vrata_ko](https://user-images.githubusercontent.com/68260701/159146361-cd213bb2-29c4-4691-afb0-6b9ba3eeb595.JPG)

**Comment by Vasika-uso** [comment]
Same problem , the model.h header seems to load correctly just the .obj files from the repository , others dont works because it doesnt load the texture coords properly. The issue is in the code , mesh viewers like MeshLab load the .obj with the texture fine.

**Comment by Vasika-uso** [comment]
found a fix for my problem , try using the shader for that chapter you use , those from src/3.model_loading worked fine for me.
