### ISSUE TITLE
why aiTextureType doesn't match your texture name

### ISSUE THREAD

**Issue by mi2think** [JoeyDeVries/LearnOpenGL#30]
In model.h,  here has:
`this->loadMaterialTextures(material, aiTextureType_HEIGHT, "texture_normal");`
and also
`this->loadMaterialTextures(material, aiTextureType_AMBIENT, "texture_height");`

why do you give  `"texture_normal"` name to `aiTextureType_HEIGHT`?  
It should be `aiTextureType_NORMALS`, right?

**Comment by JoeyDeVries** [comment]
Yes that would be the proper texture type, but the combination of Blender, Wavefront output format and Assimp I used didn't load normal maps on the texture type of aiTextureType_Normal but as aiTextureType_Height. 

I made a brief note of this in the [Normal Mapping](http://learnopengl.com/#!Advanced-Lighting/Normal-Mapping) tutorial where I added this line in:

> Then you'll also have to update the model loader to also load normal maps from a textured model. The wavefront object format (.obj) exports normal maps slightly different as Assimp's aiTextureType_NORMAL doesn't load its normal maps while aiTextureType_HEIGHT does so I often load them as...

Maybe it's something weird with Blender and/or the Wavefront output format, but that seems to work.
