### ISSUE TITLE
findSOIL.cmake doesn't work in Fedora 23

### ISSUE THREAD

**Issue by La-Stravaganza** [JoeyDeVries/LearnOpenGL#31]
Hello Joey,

Thank you for the great tutorial!

I'm using fedora 23 and installed SOIL with dnf. It turns out that the actual path to it is ``/usr/include/SOIL``, which is not mentioned in your ``findSOIL.cmake`` file.

This is only a one-line change, I can offer you a pull request if you feel appropriate.

Jinbo

**Comment by La-Stravaganza** [comment]
well, never mind. It actually works. Sorry for this wrong info

**Comment by JoeyDeVries** [comment]
Haha not a problem!
