### ISSUE TITLE
 MAC build cmake CMAKE_CXX_COMPILER error!

### ISSUE THREAD

**Issue by weiyu666** [JoeyDeVries/LearnOpenGL#314]
The Xcode project cannot be generated by compiling with cmake on Mac
CMAKE_CXX_COMPILER not found in cmake file
![企业微信截图_3ad712f3-828f-43fd-ace9-873a2e7e09c1](https://user-images.githubusercontent.com/22174508/177675227-1e5ade49-08ae-4d46-b619-353eced30c4c.png)

**Comment by SimpleCppCoder** [comment]
According to [this stackoverflow post](https://stackoverflow.com/questions/41380900/cmake-error-no-cmake-c-compiler-could-be-found-using-xcode-and-glfw), you might have to run `sudo xcode-select --reset`?

**Comment by weiyu666** [comment]
![企业微信截图_5dc04e4b-3532-4b1b-a1be-9bdaed446eb1](https://user-images.githubusercontent.com/22174508/184277263-5fe9a62e-99e8-466e-b646-491d18deeb2f.png)
problem solved~
