### ISSUE TITLE
[Request] Material loading (models without a texture, just color)

### ISSUE THREAD

**Issue by SimpleCppCoder** [JoeyDeVries/LearnOpenGL#318]
Hello again! This time I just have a feature request, not a bug report. Can you add a section in the model loading tutorial for loading materials? Materials as in models that do not have a texture, just a color. Thanks! Love the tutorials so far!

**Comment by LooksForFuture** [comment]
I think you're doing it wrong because loaded objects have textures.

**Comment by gameengineer** [comment]
The OBJ model files can have materials defined with texture files or not. His question is valid.

**Comment by JoeyDeVries** [comment]
Materials can indeed have colors, just colors, or combination of colors and textures; and of course as many variations as you'd like so the sky is the limit. There are definitely few 'standard' ways of approaching this and allowing for pure color materials is one of them. I don't expect I'll be writing more new tutorials as new efforts I'd like to focus on Vulkan and quite busy at the moment, but I did note it down; it would be a great addition to discuss material setups. When I find time to work on Vulkan I'll see if I can write a chapter about that as well :)
