### ISSUE TITLE
Correction for "getNormalFromMap()" in PBR Texturing Tutorial

### ISSUE THREAD

**Issue by cybereality** [JoeyDeVries/LearnOpenGL#344]
This line in the function `vec3 getNormalFromMap()` is incorrect.

`vec3 tangentNormal = texture(normalMap, TexCoords).xyz * 2.0 - 1.0;`

It should take all components into account:

`vec3 tangentNormal = texture(normalMap, TexCoords).xyz * 2.0 - vec3(1.0);`

**Comment by cybereality** [comment]
Actually, you're right. I changed it back to your way and things work fine. I did have a weird glitch before, and I was pretty sure it was caused by that line, but now I am unable to reproduce it. Sorry for the confusion.

**Comment by JoeyDeVries** [comment]
Ahah no worries, always better to make sure! Good luck!
