### ISSUE TITLE
Porting to native android c++

### ISSUE THREAD

**Issue by nativeAndroid** [JoeyDeVries/LearnOpenGL#37]
Hi dear friend,
I would like to port it / rewrite some parts of your code for native android application.
May I do that ?  ( I won't get trouble )

Thank you for reading

**Comment by JoeyDeVries** [comment]
All code of learnopengl.com is in the public domain so you can use it however you like :)  
See here (http://learnopengl.com/#!About)

**Comment by nativeAndroid** [comment]
Thank you
