### ISSUE TITLE
Website is Down

### ISSUE THREAD

**Issue by RoboMage** [JoeyDeVries/LearnOpenGL#372]
![Screenshot 2023-10-29 141828](https://github.com/JoeyDeVries/LearnOpenGL/assets/27884887/f2cd806c-c8cd-4ca7-a1a3-2a7eb8a7ded4)

Site reads :
"Not Acceptable!

An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security."

**Comment by GammaSigma1234** [comment]
Same here.

**Comment by JoeyDeVries** [comment]
Yes, thank you for letting me know! I'm chatting with my hosting provider now. They have some kind of security filter url verification check system that seems to be generating false positives on my website now for some reason. Hoping they can fix this quickly!

**Comment by JoeyDeVries** [comment]
Phew, okay it's back up and running again; thanks all for letting me know, cheers!

**Comment by RoboMage** [comment]
Glad you got the site back up so fast! Thanks again for all your work  :)

**Comment by ArcE404** [comment]
Thank you for giving such a quick solution! 😄

**Comment by JoeyDeVries** [comment]
Not at all, thank you! 😁
