### ISSUE TITLE
glad is no longer down

### ISSUE THREAD

**Issue by Dav1dde** [JoeyDeVries/LearnOpenGL#377]
The tutorial lists the website as down:

> Update (October 10th, 2023): Unfortunately the website seems to be down. If you get the latest from the [GLAD](https://github.com/Dav1dde/glad) repo, switch to the master branch, and run the following Python command (you'll have to install Python) [...]

That was a small hiatus with my hosting provider who decided to shutdown their services, I am back to self-hosting and it's been up and running since.

I was looking to make a PR but couldn't find the actual doc sources.

**Comment by JoeyDeVries** [comment]
Glad to hear it's resolved, thanks for letting me know! I've updated the text so it's correct again.

And thank you for Glad! 🙏
