### ISSUE TITLE
Segfault at introduction to textures chapter, fix attached

### ISSUE THREAD

**Issue by Darshan-2021-11** [JoeyDeVries/LearnOpenGL#378]
the `unsigned char* data` variable is freed using `stb_image_free(data)` after loading the first texture only to be reused later on to load the 2nd texture causing segmentation fault. Should be an easy fix, just remove the line no. 115 from https://github.com/JoeyDeVries/LearnOpenGL/blob/master/src/1.getting_started/4.1.textures/textures.cpp file, and your file is up and running successfully.

**Comment by JoeyDeVries** [comment]
I think it must be something else causing a segfault on your end, as `data` is only used before the `stb_image_free(data)`. When another load call is issued, `data` is only used after (and checked for validness) on all texture chapters.

**Comment by Darshan-2021-11** [comment]
Now when I readded the line, it does work, what we are doing essentially is reusing the pointer, which should be an issue, I think it was a fault from my end. Maybe something else was off in *my particular setup*

**Comment by JoeyDeVries** [comment]
Good to hear, glad it's resolved, cheers!
