### ISSUE TITLE
Motivation: rewrite the codebase in Rust

### ISSUE THREAD

**Issue by srcres258** [JoeyDeVries/LearnOpenGL#395]
Dear @JoeyDeVries ,

I've been learning Rust for a while and learning OpenGL simultaneously. Is it convenient for you to include the Rust version code based on the existing C-written code logic to this repository? I'm glad to give the readers a different flavor of implementations of OpenGL in a novel language and migrate the old code to a new language which is booming nowadays.

Looking forward to your reply. :)

**Comment by JoeyDeVries** [comment]
Thank you for the offer :) but I do like to keep everything here C-written as it's directly linked to the website/book and adding extra languages that aren't directly mentioned in the text would convolute things somewhat I find. Not by much, but I'd rather it be a separate thing. Hope you understand!

**Comment by srcres258** [comment]
> Thank you for the offer :) but I do like to keep everything here C-written as it's directly linked to the website/book and adding extra languages that aren't directly mentioned in the text would convolute things somewhat I find. Not by much, but I'd rather it be a separate thing. Hope you understand!

Got it. In this case, would it be possible for you to add a link or introduction to my Rust-version repository as the separation so that my code won't interfere with yours?

**Comment by gameengineer** [comment]
Keep this great site and codebase to C++ which is still very relevant in professional , commercial applications today. I am speaking as one in the software industry. If you introduce the code base for this site in one language where do you stop? My advice would be to put in the effort this author did by creating and promoting a site of your own with your version of the code base if this author allows the copyright.

**Comment by JoeyDeVries** [comment]
Yes, if your Rust repo is big enough I'd be happy to mention it in the readme, and code repository page of LearnOpenGL :)

**Comment by srcres258** [comment]
> Yes, if your Rust repo is big enough I'd be happy to mention it in the readme, and code repository page of LearnOpenGL :)

Thanks! I'll move on to my work then.

**Comment by JoeyDeVries** [comment]
Sorry for the delay, had a few busy weeks. Writing now to tell you I haven't forgotten you. I will be able to make some time for this soon! 🙏

**Comment by JoeyDeVries** [comment]
Took a while, but I added your repo to the readme and LearnOpenGL's code repository page, thank you!
