### ISSUE TITLE
Site seems to be down

### ISSUE THREAD

**Issue by WDoughty** [JoeyDeVries/LearnOpenGL#408]
Any page other than the home page seems to not be loading correctly.

**Comment by bramtechs** [comment]
Can confirm.

**Comment by JoeyDeVries** [comment]
I see it as well, thnx for letting me know. Looking into it right now.

**Comment by JoeyDeVries** [comment]
As copied from x.com: "LearnOpenGL is down, some weird PHP glitch it seems. It has likely something to do with a global PHP change at my host provider. No clue how to fix it on my end yet and it's getting late; will have to look for a fix tomorrow. Apologies for the inconvenience!"

Can't do anything but wait for a response from my hosting provider now, will update when I can, my apologies!

**Comment by JoeyDeVries** [comment]
Sorry for the big delay. I have just resolved it with my hosting provider. The web-server updated the PHP version to 8.2 that apparently wasn't backwards compatible with the LearnOpenGL backend. It's resolved now, happy graphics programming! ⌨️

(and thanks again for letting me know!)
