### ISSUE TITLE
A issue about the params of glm::perspective()

### ISSUE THREAD

**Issue by JettHuang** [JoeyDeVries/LearnOpenGL#46]
The following codes calculates the perspective matrix: 
       // Create camera transformations
        glm::mat4 view;
        view = camera.GetViewMatrix();
        glm::mat4 projection = glm::perspective(camera.Zoom, (GLfloat)WIDTH / (GLfloat)HEIGHT, 0.1f, 100.0f);

I found the camera.Zoom is degree but not radians,   so we got a strange result.
we should use  camera.Zoom/glm::two_pi<float>()  as fovy.

**Comment by JoeyDeVries** [comment]
I know, I'll soon do a code sweep on all older tutorials, replacing SOIL and GLEW and also updating all degrees to radians, thank you! 

Note that you can also use `glm::radians(degrees)` to convert from degrees to radians.

**Comment by JoeyDeVries** [comment]
Code sweep is close to complete, with every relevant argument now properly converted to radians. I'll reflect this in the text as well in the upcoming weeks.
