### ISSUE TITLE
Model.cpp incorrect c_string comparison

### ISSUE THREAD

**Issue by htmlboss** [JoeyDeVries/LearnOpenGL#49]
Me again! 😝 

In the `loadMaterialTextures(...)` function, where you check if the texture has already been loaded:

```
if(textures_loaded[j].path == str)
            {
                textures.push_back(textures_loaded[j]);

                skip = true; 

                break;
            }
```

The if-check needs to be changed to: 

```
if(std::strcmp(textures_loaded[j].path, str) == 0)
            {
                textures.push_back(textures_loaded[j]);

                skip = true; 

                break;
            }
```
The strcmp function lexicographically compares null-terminated byte strings and returns 0 if equal, otherwise 1. Simply checking for equality (using `==`) doesn't work. This bug appears to only rear its head with complex models that share textures (because the nanosuit is simple, that's probably why no one has caught it yet).

I was tearing my hair out trying to figure out why the "Crytek Sponza" model was eating up 3GB of memory and generating 400 GL textures. This was why because the equality operator was generating undefined behaviour😛 Now it creates 24 textures and uses 600MB memory!

[http://en.cppreference.com/w/cpp/string/byte/strcmp](http://en.cppreference.com/w/cpp/string/byte/strcmp)

If you don't have the time, I can make a quick fork and submit a PR within a day or so.

**Comment by JoeyDeVries** [comment]
Aii, that's a stupid mistake; right now it's simply comparing pointers which is obviously not going to work. Thanks for catching it! And no worries, I already updated it in the repository, code samples and the tutorial :) Thanks again!
