### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by gambhiro** [JoeyDeVries/LearnOpenGL#5]
In the README on Linux deps, did you mean `libglfw3-dev`? Without `3`, the default package is v2.

**Comment by JoeyDeVries** [comment]
I didn't write the linux part of the readme, but the tutorials do use 
GLFW3 so I'd say yes, with the 3. In that case I'll update it in the 
readme, thanks :)

Gambhiro schreef op 7-4-2015 om 18:03:
