### ISSUE TITLE
Shadow Mapping problems...

### ISSUE THREAD

**Issue by standtall007** [JoeyDeVries/LearnOpenGL#50]
Hi Joey, i honestly don't know if you would see this message if i would have sent it to your website, but i have ggotten a problem with shadow mapping, and i have followed your tutorial very closely but still, i have this problem that my shadow (on a small scene made of cubes and a plane to look like a really basic military base) is somehow shown from above at an angle, it makes my scene really ugly, but i have tried everything and i just don't know how to fix it... i hope that since it is your tutorial i have followed that you could maybe help me out?

Thanks in advance,
David.

**Comment by standtall007** [comment]
i have a picture of what i mean here:
[http://nutcrackz.com/shadowmapping.png](url)

**Comment by JoeyDeVries** [comment]
Without images to show you what's wrong it's difficult to figure out what's wrong. Then some source code might also be useful and did you check the following:

- first display your shadow depth map directly to the screen, if this looks wrong you know the issue is in your shadow map generation.
- adjust bias?
- adjusted the orthographic frustum to encompass all objects in your scene?

**Comment by standtall007** [comment]
`GLuint Viewport3D::ShadowMapFBO()
{
        glGenFramebuffers(1, &depthMapFBO);
	// - Create depth texture
	glGenTextures(1, &depthMap);
	glBindTexture(GL_TEXTURE_2D, depthMap);

	glTexImage2D(GL_TEXTURE_2D, 0, GL_DEPTH_COMPONENT, SHADOW_WIDTH, SHADOW_HEIGHT, 0, GL_DEPTH_COMPONENT, GL_FLOAT, NULL);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_BORDER);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_BORDER);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_COMPARE_MODE, GL_COMPARE_R_TO_TEXTURE);

	GLfloat borderColor[] = { 1.0, 1.0, 1.0, 1.0 };
	glTexParameterfv(GL_TEXTURE_2D, GL_TEXTURE_BORDER_COLOR, borderColor);

	glBindFramebuffer(GL_FRAMEBUFFER, depthMapFBO);
	glFramebufferTexture2D(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_TEXTURE_2D, depthMap, 0);

	glDrawBuffer(GL_NONE);
	glReadBuffer(GL_NONE);

	return depthMapFBO;
}

GLuint shade;
bool test = false;

glm::mat4 lightSpaceMatrix;

// Light source
glm::vec3 lightPos(-2.0f, 4.0f, -1.0f);

//This is the depth rendering pass!
void Viewport3D::RenderPass(float dt, int z)
{
	if (!test)
	{
		shade = ShadowMapFBO();
		test = true;
	}

	glm::mat4 lightProjection = glm::ortho(-10.0f, 10.0f, -10.0f, 10.0f, near_plane, far_plane);

	glm::mat4 lightView = glm::lookAt(lightPos, glm::vec3(0.0f), glm::vec3(0.0f, 1.0f, 0.0f));

	lightSpaceMatrix = lightProjection * lightView;

	simpleDepthShader.use();

	glUniformMatrix4fv(glGetUniformLocation(simpleDepthShader.getProgram(), "lightSpaceMatrix"), 1, GL_FALSE, glm::value_ptr(lightSpaceMatrix));

	glViewport(0, 0, SHADOW_WIDTH, SHADOW_HEIGHT);
	glBindFramebuffer(GL_FRAMEBUFFER, depthMapFBO);
	glClear(GL_DEPTH_BUFFER_BIT);

	for (std::vector<GameObjects*>::iterator iter = gameObjects.begin(); iter != gameObjects.end(); iter++)
	{
		glm::mat4 _objmodel;

		for (unsigned int i = 0; i < gameObjects.size(); i++)
		{
			gameObjects[i]->go = *gameObjects3D[i];
		}

		_objmodel = glm::translate(_objmodel, (*iter)->getPosition());
		_objmodel = glm::rotate(_objmodel, glm::radians((*iter)->go.getRotation().x * sin(1.575f)), glm::vec3(1.0f, 0.0f, 0.0f));
		_objmodel = glm::rotate(_objmodel, glm::radians((*iter)->go.getRotation().y * sin(1.575f)), glm::vec3(0.0f, 1.0f, 0.0f));
		_objmodel = glm::rotate(_objmodel, glm::radians((*iter)->go.getRotation().z * sin(1.575f)), glm::vec3(0.0f, 0.0f, 1.0f));
		_objmodel = glm::scale(_objmodel, (*iter)->go.getScale());

		glUniformMatrix4fv(glGetUniformLocation(simpleDepthShader.getProgram(), "model"), 1, GL_FALSE, glm::value_ptr(_objmodel));

		(*iter)->getObjectModel()->Draw(shader);
	}

	for (std::vector<MD5GameObjects*>::iterator iter = md5gameObjects.begin(); iter != md5gameObjects.end(); iter++)
	{
		glm::mat4 _md5model;

		for (unsigned int i = 0; i < md5gameObjects.size(); i++)
		{
			md5gameObjects[i]->go = *md5gameObjects3D[i];
		}

		_md5model = glm::translate(_md5model, (*iter)->go.getPosition());
		_md5model = glm::rotate(_md5model, glm::radians((*iter)->go.getRotation().x * sin(1.575f)), glm::vec3(1.0f, 0.0f, 0.0f));
		_md5model = glm::rotate(_md5model, glm::radians((*iter)->go.getRotation().y * sin(1.575f)), glm::vec3(0.0f, 1.0f, 0.0f));
		_md5model = glm::rotate(_md5model, glm::radians((*iter)->go.getRotation().z * sin(1.575f)), glm::vec3(0.0f, 0.0f, 1.0f));
		_md5model = glm::scale(_md5model, (*iter)->go.getScale());

		glUniformMatrix4fv(glGetUniformLocation(simpleDepthShader.getProgram(), "model"), 1, GL_FALSE, glm::value_ptr(_md5model));

		(*iter)->getMD5Model()->Render();
	}

	for (std::vector<GameObjects*>::iterator iter = gameObjects.begin(); iter != gameObjects.end(); iter++)
	{
		if ((*iter)->go.m_type == ObjectType::MODELOBJECT)
		{
			int tmpVar1 = pLights.size() + sLights.size() + dirLights.size();
			int tmpVar2 = gameObjects.size() - tmpVar1;

			if (objSize < tmpVar2)
			{
				objSize++;

				Nutcrackz::Editor neditor;
				neditor.clearConsoleScreen();
				resetScreen();
			}
		}

		glm::mat4 _objmodel1;

		_objmodel1 = glm::translate(_objmodel1, (*iter)->getPosition());

		_objmodel1 = glm::rotate(_objmodel1, glm::radians((*iter)->go.getRotation().x * sin(1.575f)), glm::vec3(1.0f, 0.0f, 0.0f));
		_objmodel1 = glm::rotate(_objmodel1, glm::radians((*iter)->go.getRotation().y * sin(1.575f)), glm::vec3(0.0f, 1.0f, 0.0f));
		_objmodel1 = glm::rotate(_objmodel1, glm::radians((*iter)->go.getRotation().z * sin(1.575f)), glm::vec3(0.0f, 0.0f, 1.0f));

		_objmodel1 = glm::scale(_objmodel1, (*iter)->go.getScale());
	}

	for (std::vector<MD5GameObjects*>::iterator iter = md5gameObjects.begin(); iter != md5gameObjects.end(); iter++)
	{
	        glm::mat4 _md5model1;

		_md5model1 = glm::translate(_md5model1, (*iter)->go.getPosition());
		_md5model1 = glm::rotate(_md5model1, glm::radians((*iter)->go.getRotation().x * sin(1.575f)), glm::vec3(1.0f, 0.0f, 0.0f));
		_md5model1 = glm::rotate(_md5model1, glm::radians((*iter)->go.getRotation().y * sin(1.575f)), glm::vec3(0.0f, 1.0f, 0.0f));
		_md5model1 = glm::rotate(_md5model1, glm::radians((*iter)->go.getRotation().z * sin(1.575f)), glm::vec3(0.0f, 0.0f, 1.0f));
		_md5model1 = glm::scale(_md5model1, (*iter)->go.getScale());
	}

	glBindFramebuffer(GL_FRAMEBUFFER, 0);

	simpleDepthShader.unuse();
}

//This is the normal rendering pass!
void Viewport3D::RenderPass(float dt)
{
	glViewport(0, 0, getWidth(), getHeight());
	glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

	m_pEffect.use();

	glUniformMatrix4fv(glGetUniformLocation(m_pEffect.getProgram(), "projection"), 1, GL_FALSE, glm::value_ptr(projection));
	glUniformMatrix4fv(glGetUniformLocation(m_pEffect.getProgram(), "view"), 1, GL_FALSE, glm::value_ptr(view));
	
	// Set light uniforms
	glUniform3fv(glGetUniformLocation(m_pEffect.getProgram(), "lightPos"), 1, &lightPos[0]);
	glUniform3fv(glGetUniformLocation(m_pEffect.getProgram(), "viewPos"), 1, &camera.getPosition()[0]);
	glUniformMatrix4fv(glGetUniformLocation(m_pEffect.getProgram(), "lightSpaceMatrix"), 1, GL_FALSE, glm::value_ptr(lightSpaceMatrix));
	// Enable/Disable shadows by pressing 'SPACE'
	glUniform1i(glGetUniformLocation(m_pEffect.getProgram(), "shadows"), true);

	m_pEffect.SetTextureUnit(0);
	m_pEffect.SetNormalMapTextureUnit(1);
	m_pEffect.SetShadowMapTextureUnit(2);

	glActiveTexture(GL_TEXTURE1);
	glBindTexture(GL_TEXTURE_2D, depthMap);

	m_pEffect.SetSpotLights(sLights.size(), sLights);

	m_pEffect.SetPointLights(pLights.size(), pLights);

	if (hasCreatedDirLight)
	{
		m_pEffect.SetDirectionalLight(*dirLights[0]);
	}
	else
	{
		m_pEffect.SetDirectionalLight(m_directionalLightBlank);
	}

	for (std::vector<GameObjects*>::iterator iter = gameObjects.begin(); iter != gameObjects.end(); iter++)
	{
		glUniform1i(glGetUniformLocation(m_pEffect.getProgram(), "isAnimated"), false);

		glm::mat4 _objmodel;

		for (unsigned int i = 0; i < gameObjects.size(); i++)
		{
			gameObjects[i]->go = *gameObjects3D[i];
		}

		_objmodel = glm::translate(_objmodel, (*iter)->getPosition());
(*iter)->go.getPosition().y, (*iter)->go.getPosition().z, -9.81f, dt));
		_objmodel = glm::rotate(_objmodel, glm::radians((*iter)->go.getRotation().x * sin(1.575f)), glm::vec3(1.0f, 0.0f, 0.0f));
		_objmodel = glm::rotate(_objmodel, glm::radians((*iter)->go.getRotation().y * sin(1.575f)), glm::vec3(0.0f, 1.0f, 0.0f));
		_objmodel = glm::rotate(_objmodel, glm::radians((*iter)->go.getRotation().z * sin(1.575f)), glm::vec3(0.0f, 0.0f, 1.0f));
		_objmodel = glm::scale(_objmodel, (*iter)->go.getScale());

		glUniformMatrix4fv(glGetUniformLocation(m_pEffect.getProgram(), "model"), 1, GL_FALSE, glm::value_ptr(_objmodel));

			(*iter)->getObjectModel()->hasLoadedPrevTexes = false;
		}
	}

	for (std::vector<MD5GameObjects*>::iterator iter = md5gameObjects.begin(); iter != md5gameObjects.end(); iter++)
	{
		glUniform1i(glGetUniformLocation(m_pEffect.getProgram(), "isAnimated"), false);

		glm::mat4 _md5model;

		for (unsigned int i = 0; i < md5gameObjects.size(); i++)
		{
			md5gameObjects[i]->go = *md5gameObjects3D[i];
		}

		_md5model = glm::translate(_md5model, (*iter)->go.getPosition());
		_md5model = glm::rotate(_md5model, glm::radians((*iter)->go.getRotation().x * sin(1.575f)), glm::vec3(1.0f, 0.0f, 0.0f));
		_md5model = glm::rotate(_md5model, glm::radians((*iter)->go.getRotation().y * sin(1.575f)), glm::vec3(0.0f, 1.0f, 0.0f));
		_md5model = glm::rotate(_md5model, glm::radians((*iter)->go.getRotation().z * sin(1.575f)), glm::vec3(0.0f, 0.0f, 1.0f));
		_md5model = glm::scale(_md5model, (*iter)->go.getScale());

		glUniformMatrix4fv(glGetUniformLocation(m_pEffect.getProgram(), "model"), 1, GL_FALSE, glm::value_ptr(_md5model));

		m_pEffect.SetShaderParameters((*iter)->getMD5Model()->GetSkinnedMatrices());
		(*iter)->getMD5Model()->Render();
	}
	
	m_pEffect.unuse();
}`

the near and far plane i have in the header of this script! they are set to : near_plane = 1.0f; far_plane = 7.5f;

**Comment by standtall007** [comment]
> adjusted the orthographic frustum to encompass all objects in your scene?

i have never been good at understanding the frustum meaning, but do you basically mean the camera's position?

> first display your shadow depth map directly to the screen, if this looks wrong you know the issue is in your shadow map generation.

This is easy to answer since when i had it to render on the entire screen it simply shows black, and nothing else, but i am lost when it comes to solve it... i don't know if it has something to do that i'm using wxWidgets as my window?

**Comment by JoeyDeVries** [comment]
Please format your code, or use something like https://gist.github.com/

**Comment by standtall007** [comment]
Hi Joey i have just updated the code to be used on gist instead please look at the link :)

**Comment by standtall007** [comment]
Hi Joey, i have just been tinkering with the code (mostly removed comments and reverted some code that didn't change anything on the screen anyway!) and i can now see the depthMap (or rather some of it) when i render the quad! but the shadow in the depth map (or the blackness if you want) is static it doesn't follow the camera, or it doesn't change position inside the quad... i will gladly send you a screenshot :)

here is the screenshot: [http://nutcrackz.com/shadowmapping2.png](url)

i have also tried to tinker with the projCoords in the fragment shader, i have tried to change the z coord to both x and y, it does change the shadow position and rotation but it still does not look right...

**Comment by standtall007** [comment]
Hi Joey, i want to thank you for making me try harder even if you're still asleep :) i have FINALLY gotten it to work that to the way you wrote the things :D i didn't take it as a kick in the crotch, but instead it encouraged me to try all night to get it to work :) and now it does, so Thank you very much!

Cheers, and i am looking forward to your next tutorial ;-)

**Comment by JoeyDeVries** [comment]
Haha great to hear and yes I was asleep, sorry :) Great that you managed to fix it, best of luck!

**Comment by standtall007** [comment]
no problem :D i am just so excited that i finally can relax on the whole shadow mapping part of my engine :D i have also made it work with my own scripts so i don't use yours for the engine ;-) i hope you got some rest btw :)
