### ISSUE TITLE
Floor Size Difference between 'Advanced Lighting' and 'Gamma Correction'

### ISSUE THREAD

**Issue by bryanwagner** [JoeyDeVries/LearnOpenGL#52]
Hi Joey, these tutorials are seriously the best.  I ran into a gotcha between the two aforementioned tutorials and this is just a suggestion to prevent anyone else from running into it too.

I noticed a difference in lighting between my implementation of 'Gamma Correction' from the repository version; my version seemed several shades darker.  I spent about an hour tracking down what it was because I knew I had to get this right to make sure I was handling gamma correction the right way.

What I had done was use the code I wrote while following the 'Advanced Lighting' tutorial as a template for 'Gamma Correction'.  My mistake was that the model data for the size of the floor changes from 8x8 units to 5x5 units between the two.  My 'floor' was wider than the repository demo, so the light hits less area, and the surface 'appears' darker.  Missing this made me think I had errors in handling gamma.

I recommend changing the model size in 'Advanced Lighting' to 5x5 units since the model size doesn't affect that tutorial as much; this would keep anyone else from making the same mistake. Anyway, just a suggestion!

**Comment by JoeyDeVries** [comment]
I agree, it's definitely relevant to keep things consistent wherever I can (especially when there's really no need to change the floor size). I've just finished the PBR tuts, so I'm currently working on a major code update on all samples. I'll definitely put your suggestion in! 

Thanks! :)

**Comment by bryanwagner** [comment]
Awesome timing as I'm just approaching PBR! Thanks again, this is an invaluable resource.

**Comment by JoeyDeVries** [comment]
They should be the same dimensions now.
