### ISSUE TITLE
IBL textured example does not copy over all required shaders

### ISSUE THREAD

**Issue by SaschaWillems** [JoeyDeVries/LearnOpenGL#54]
The IBL specular textured example uses multiple shaders from the previous example:

    Shader equirectangularToCubemapShader("2.2.1.cubemap.vs", "2.2.1.equirectangular_to_cubemap.frag");
    Shader irradianceShader("2.2.1.cubemap.vs", "2.2.1.irradiance_convolution.frag");
    Shader prefilterShader("2.2.1.cubemap.vs", "2.2.1.prefilter.frag");
    Shader brdfShader("2.2.1.brdf.vs", "2.2.1.brdf.frag");
    Shader backgroundShader("2.2.1.background.vs", "2.2.1.background.frag");

But the pre build event will only copy the two pbr shaders and needs to be adjusted. 

Just a minor issue as you can still copy over the shaders manually to run the sample.

**Comment by JoeyDeVries** [comment]
Yeah I'm still not sure what the right solution is here. I didn't add a shader set specifically for the IBL specular texture example as the shaders you listed are **exactly** the same. Having to copy them over for that example would mean whenever I do maintenance on any of these shaders, I'd have to do them twice (let alone other examples that also share shaders). So I made the decision to only keep one shader set.

This does indeed mean that when you **only** build the IBL specular texture example without first building the IBL specular example you're missing the shaders. I thought this was okay as most people tend to build everything anyways in which case the shaders will be there, but appareantly not in all cases (which I guess makes sense too as I can definitely imagine people only want to run a specific example).

So it's a bit of a dilemma. I'll probably have to delve a bit deeper into CMake to see if I can think of something that allows me to set up dependency chains so I can run pre-build scripts on dependent projects.

**Comment by SaschaWillems** [comment]
I can understand that this is not easy. For my Vulkan example I decided not to go with cmake (as it's not available on all supported platforms) and just put all shaders into an asset folder relative to where the binaries are put like you do with the resource folder, but that doesn't really help with shader duplication unless you put all shaders into one big folder.

**Comment by JoeyDeVries** [comment]
Yeah, once I'm done converting every code sample to its GitHub equivalent (with Glad and stb_image.h) I'll try solving this issue. My preferred approach would be to let CMake handle it, so I'll try and look if I can implement something of a dependency system within the CMakeLists.txt file.

By the way, I took a look at your Vulkan demo repository and hats off to you! It's incredibly well setup and the documentation and samples look great. I'll definitely take a close look at your repository once I start getting serious about Vulkan, thanks!

**Comment by JoeyDeVries** [comment]
I've decided to simply copy the relevant shaders over to each required directory, even if I may end up with duplicated code. It's convenient for me to keep all relevant shaders in the same folder as this benefits the code viewer as well. All in all a fair compromise.

If you get the latest commit, the shaders should properly copy over for each PBR example (note that some of the other non-PBR tutorials still don't copy all shaders over; I'll work on this in the upcoming weeks).
