### ISSUE TITLE
Increase pre-filtered cubemap size for IBL examples

### ISSUE THREAD

**Issue by SaschaWillems** [JoeyDeVries/LearnOpenGL#55]
The pre-filtered cubemap should get a slight size bump. The 128x128 dimension makes up for some ugly artifacts and steps on metallic objects if you get closer to them.

Since generating the pre-filtered cubemap is pretty fast, bumping resolution up to the same size as the environment map it's based on should be fine. At least on my GTX 980 generation doesn't take much longer.

![2017-04-08 18_30_05-learnopengl](https://cloud.githubusercontent.com/assets/10283127/24830692/1e776146-1c8b-11e7-91d6-97504a3b3bb0.png)

**Comment by JoeyDeVries** [comment]
In my opinion 128x128 is fine for most materials, unless you have a simulation where almost everything is reflective (like a car game) or it's possible to get real close to objects (like you've shown). I've made a comment in the tutorial that based on this you might (indeed) want to increase the specular map.

The pre-compute speed of the pre-filtering itself isn't too relevant in my opinion (so I agree), but what can make a difference is when sampling the pre-filter map in the PBR shaders, as a 128x128 cubemap is likely to be more cache-friendly and thus save a bit of performance. It's likely to be marginal, but seeing as for most simulations 128x128 will be fine I'd like to keep them at that resolution for the tutorials (with of course the note that you may want to increase the resolution based on your setup).

**Comment by SaschaWillems** [comment]
I think the note in the tutorial is sufficient, so people realize that they may have to bump up resolution if required.

As for the pre-computation speed you may want to take a look at [this article](https://placeholderart.wordpress.com/2015/07/28/implementation-notes-runtime-environment-map-filtering-for-image-based-lighting/) which has a method that looks good at only 32 samples 😉

**Comment by JoeyDeVries** [comment]
Awesome, I've linked the article below the specular IBL tutorial; great find!
