### ISSUE TITLE
Mixture of glad and glew causing issues - PBR tutorials

### ISSUE THREAD

**Issue by mfrancis107** [JoeyDeVries/LearnOpenGL#57]
If I understand correct glew and glad hold the same purpose in your PBR tutorials you are using glew where as the rest of them you are using glad?

**Comment by mfrancis107** [comment]
Ha. I just read your last commit. Nevermind.

**Comment by JoeyDeVries** [comment]
Haha yeah exactly, I've been working hard on getting the new code re-work out there as fast as I can to make sure the repository still compiles. I'm almost there in completely removing both GLEW and SOIL, probably tonight or tomorrow I can completely remove GLEW from the repository :)
