### ISSUE TITLE
Textures tutorial references incorrect uniform names

### ISSUE THREAD

**Issue by Pendla** [JoeyDeVries/LearnOpenGL#78]
In the getting started tutorial about textures, the uniforms are set with the names `texture1` and `texture1` respectively, while in the shaders the uniforms are named `ourTexture1` and `ourTexture2`.

Note that the source code is correct and has `texture1` and `texture2` in both places.

Referenced tutorial: [https://learnopengl.com/#!Getting-started/Textures](https://learnopengl.com/#!Getting-started/Textures)

**Comment by JoeyDeVries** [comment]
Fixed, thanks!
