### ISSUE TITLE
error in run example

### ISSUE THREAD

**Issue by thewoz** [JoeyDeVries/LearnOpenGL#88]
Hi,

when I try to run any example I have the following errors:

ERROR::SHADER::FILE_NOT_SUCCESFULLY_READ
ERROR::PROGRAM_LINKING_ERROR of type: PROGRAM
ERROR: Compiled vertex shader was corrupt.
ERROR: Compiled fragment shader was corrupt.

My steps have been:

1) mkdir build
2) cmake ..
3) make -j8

**Comment by rossanag** [comment]
Sorry if I came across with the obvious, but I had the same error and it was due to an incorrect path of the file I was pointing at. 
Did you check if the file's path is set correctly? Try to put a break pint or cout where the read is made. If the shader file couldn't be read, as a consequence it won't compile.

**Comment by thewoz** [comment]
You have right!

The executables created by the make command have been installed in:

/LearnOpenGL/build/bin/1.[...]

However, the make command does not copy the shaders into the same directory where the executable is installed.

I do not understand this behaviour.

I noticed that in loading the resources is used FileSystem::getPath().
Why this is does not for the shaders?

**Comment by JoeyDeVries** [comment]
The CMake is configured s.t. it runs a shader copy command on each build, copying the relevant shader files to the executable directory as shown below:
```
if(WIN32)
    add_custom_command(TARGET ${NAME} PRE_BUILD COMMAND ${CMAKE_COMMAND} -E copy ${SHADER} $<TARGET_FILE_DIR:${NAME}>)
elseif(UNIX)
    file(COPY ${SHADER} DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/bin/${CHAPTER}/${CMAKE_BUILD_TYPE})
endif(WIN32)
```
It could be that there's something off with the elseif not firing due to some CMake subtleties (I'm not an expert on CMake). You may want to check up on that and push a fix specifically for Linux users.

**Comment by thewoz** [comment]
Hi, the problem is that line:

      file(COPY ${SHADER} DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/bin/${CHAPTER}/${CMAKE_BUILD_TYPE})

copy the shaders in ${CMAKE_CURRENT_BINARY_DIR}/bin/${CHAPTER}/${CMAKE_BUILD_TYPE})

in my case, for example, in 

~/Research/LIBRARIES/LearnOpenGL/build/bin/5.advanced_lighting/Debug/

while the executables are copy in 

~/Research/LIBRARIES/LearnOpenGL/build/bin/5.advanced_lighting/

**Comment by thewoz** [comment]
For me the solution should be to change the line 189 and 191, in the CMakeLists.txt, in the following way:

    if(WIN32)
          set_target_properties(${NAME} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/bin/${CHAPTER}/${CMAKE_BUILD_TYPE}")
     elseif(UNIX)
          set_target_properties(${NAME} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/bin/${CHAPTER}/${CMAKE_BUILD_TYPE}")
     endif(WIN32)

adding to the path for the executables ${CMAKE_BUILD_TYPE}

**Comment by JoeyDeVries** [comment]
FileSystem::getPath() would seem the proper solution, but it conflicts with the way I set up the code_viewers on the site, as it automatically tracks shader files in the same directory for linking to them. It'll be trickier to get that to work from arbitrary file paths. 

I think I'll prefer the option to remove the $(CMAKE_BUILD_TYPE) alltogether on the linux path (as it is on the other platform paths as well). Users would generally build with one compiler version anyways (and even if they do, no harm in overwriting other compiler builds) and saves some extra directory traversal. Could you remove the $(CMAKE_BUILD_TYPE) folder from the CMakeLists.txt file and see if it works? If so, send me a pull request with the fix; or I'll fix it tonight. Thanks!

**Comment by JoeyDeVries** [comment]
I took a look at the CMakeLists.txt commit history. @dotlive added the $(CMAKE_BUILD_TYPE) to the unit shader copy command which appareantly fails on MacOS. @dotlive, did you have the same issues here?

**Comment by thewoz** [comment]
I try to remove alltogether the $(CMAKE_BUILD_TYPE) on the linux path and it works.

**Comment by JoeyDeVries** [comment]
Alright, let's use that as the solution for now. We'll have to check with @dotlive then why that approach doesn't work on MacOS builds.
