### ISSUE TITLE
This is really an awesome textbook, can I translate it into Chinese?

### ISSUE THREAD

**Issue by cycleuser** [JoeyDeVries/LearnOpenGL#91]
As a newbie on computer graphics, I really enjoy your magnificent tutorial.
Could I get the permission to translate it to Chinese and share with more people?
I am a fan of computer and used to translate the CS 229 from Stanford and STA 663 from Duke.

**Comment by JoeyDeVries** [comment]
Thank you! You may want to take a look the translation work by the @LearnOpenGL-CN team, they did a wonderful job translating the tutorials to Chinese: https://learnopengl-cn.github.io/. Maybe they require additional assistance in their translation efforts?

**Comment by cycleuser** [comment]
Awesome. They really did a great job.
